import "./globals.css";

export const metadata = {
  title: "أكاديمية الأدهم",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}