import {
  User,
  Phone,
  Mail,
  Calendar,
  DollarSign,
  Clock,
  Globe,
  MapPin,
  Users,
  FileText,
  Hash,
  BookOpen,
  ListChecks,
} from "lucide-react";

export const fieldLabels = {
  name: { label: "اسم الطالب", icon: <User className="w-5 h-5 text-blue-500" /> },
  age: { label: "السن", icon: <Hash className="w-5 h-5 text-blue-500" /> },
  gender: { label: "النوع", icon: <Users className="w-5 h-5 text-blue-500" /> },
  nationality: { label: "الجنسية", icon: <Globe className="w-5 h-5 text-blue-500" /> },
  residency: { label: "بلد الإقامة", icon: <MapPin className="w-5 h-5 text-blue-500" /> },
  phone: { label: "رقم الهاتف", icon: <Phone className="w-5 h-5 text-blue-500" /> },
  guardianPhone: { label: "رقم ولي الأمر", icon: <Phone className="w-5 h-5 text-blue-500" /> },
  email: { label: "البريد الإلكتروني", icon: <Mail className="w-5 h-5 text-blue-500" /> },
  subscriptionDate: { label: "تاريخ الاشتراك", icon: <Calendar className="w-5 h-5 text-blue-500" /> },
  fees: { label: "رسوم الاشتراك", icon: <DollarSign className="w-5 h-5 text-blue-500" /> },
  currency: { label: "العملة", icon: <DollarSign className="w-5 h-5 text-blue-500" /> },
  monthlySessions: { label: "عدد الحصص الشهرية", icon: <BookOpen className="w-5 h-5 text-blue-500" /> },
  sessionDuration: { label: "مدة الحصة (دقائق)", icon: <Clock className="w-5 h-5 text-blue-500" /> },
  teacher: { label: "المعلم المتابع", icon: <User className="w-5 h-5 text-blue-500" /> },
  selectedDays: { label: "أيام الحضور", icon: <Calendar className="w-5 h-5 text-blue-500" /> },
  schedule: { label: "جدول التوقيت", icon: <ListChecks className="w-5 h-5 text-blue-500" /> },
};
